# Generated by Django 3.2 on 2021-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='pubished',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
