# Generated by Django 3.2 on 2021-06-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210611_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='pubished',
            new_name='published',
        ),
    ]
