# Generated by Django 3.2 on 2021-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210611_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=350, unique=True, verbose_name='title'),
        ),
    ]
